In [1]:
import numpy as np

In [9]:
bx = np.arange(5,13)
bx

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
bx+10

array([15, 16, 17, 18, 19, 20, 21, 22])

In [11]:
bx+3

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
bx**2*2

array([ 50,  72,  98, 128, 162, 200, 242, 288], dtype=int32)

In [13]:
cx = bx.reshape(4,2)
cx

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [14]:
cx*2+20

array([[30, 32],
       [34, 36],
       [38, 40],
       [42, 44]])

In [16]:
dx = np.array([7,2])
cx*dx

array([[35, 12],
       [49, 16],
       [63, 20],
       [77, 24]])

In [17]:
cx/cx

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.sqrt(cx)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [3.        , 3.16227766],
       [3.31662479, 3.46410162]])

In [19]:
np.exp(cx)

array([[1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05]])

In [21]:
np.sin(cx)

array([[-0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111],
       [-0.99999021, -0.53657292]])

In [22]:
np.log(cx)

array([[1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509],
       [2.39789527, 2.48490665]])

In [23]:
np.log(np.exp(cx))

array([[ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]])

In [24]:
np.insert(bx,3,2000)

array([   5,    6,    7, 2000,    8,    9,   10,   11,   12])

In [25]:
np.delete(bx,6)

array([ 5,  6,  7,  8,  9, 10, 12])

In [26]:
np.append(bx,4536)

array([   5,    6,    7,    8,    9,   10,   11,   12, 4536])

In [28]:
sx = np.array([[50,89],[77,21],[60,57]])
hx = np.array([[45,23],[41,21]])
np.concatenate((sx,hx), axis=0)

array([[50, 89],
       [77, 21],
       [60, 57],
       [45, 23],
       [41, 21]])

In [33]:
np.concatenate((sx,hx.T), axis=0)

array([[50, 89],
       [77, 21],
       [60, 57],
       [45, 41],
       [23, 21]])

In [36]:
np.concatenate((sx,hx), axis=None)

array([50, 89, 77, 21, 60, 57, 45, 23, 41, 21])

In [38]:
np.where(bx%2==0,'yes','no')

array(['no', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'yes'], dtype='<U3')

In [40]:
np.where(bx%2==1,'ya','tidak')

array(['ya', 'tidak', 'ya', 'tidak', 'ya', 'tidak', 'ya', 'tidak'],
      dtype='<U5')

In [42]:
np.where(cx%2==0,'do','dont')

array([['dont', 'do'],
       ['dont', 'do'],
       ['dont', 'do'],
       ['dont', 'do']], dtype='<U4')

In [43]:
import numpy as np
import pandas as pd

In [44]:
l = ['x','y','z']
ml = [1,3,5]
arr = np.array([7,8,9])
ds = {'a' : 85, 'b' : 78, 'c' : 87}

In [45]:
pd.Series(data=ml)

0    1
1    3
2    5
dtype: int64

In [46]:
pd.Series(data=ml,index=l)

x    1
y    3
z    5
dtype: int64

In [47]:
pd.Series(arr)

0    7
1    8
2    9
dtype: int32

In [49]:
pd.Series(arr,l)

x    7
y    8
z    9
dtype: int32

In [50]:
pd.Series(ds)

a    85
b    78
c    87
dtype: int64

In [60]:
asx = [i for i in range(1,5)]
bsx = [i for i in range(5,9)]
csx = [i for i in range(9,13)]

In [66]:
df = pd.DataFrame(data=[asx,bsx,csx],
            index='a b c'.split(),
            columns='w x y z'.split())
df

w   x   y   z
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [65]:
pd.DataFrame(data=list(zip(asx,bsx,csx)),
            index = 'w x y z'.split(),
            columns = 'a b c'.split())

a  b   c
w  1  5   9
x  2  6  10
y  3  7  11
z  4  8  12

In [67]:
df

w   x   y   z
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [68]:
df.loc['new']=[2,4,6,8]
df

w   x   y   z
a    1   2   3   4
b    5   6   7   8
c    9  10  11  12
new  2   4   6   8

In [69]:
df['new'] = df['w'] + df['y']
df

w   x   y   z  new
a    1   2   3   4    4
b    5   6   7   8   12
c    9  10  11  12   20
new  2   4   6   8    8

In [77]:
df.insert(2,'apa',[1,2,3,4])
df

w   x  apa   y   z  new
a    1   2    1   3   4    4
b    5   6    2   7   8   12
c    9  10    3  11  12   20
new  2   4    4   6   8    8

In [79]:
df.drop('new',axis=1)

w   x  apa   y   z
a    1   2    1   3   4
b    5   6    2   7   8
c    9  10    3  11  12
new  2   4    4   6   8

In [80]:
df

w   x  apa   y   z  new
a    1   2    1   3   4    4
b    5   6    2   7   8   12
c    9  10    3  11  12   20
new  2   4    4   6   8    8